#! /bin/bash

for v in $*; do
	if [ -r $v ]; then
		readable="skaitomas"
	else
		readable="neskaitomas"
	fi
	
	if [ -x $v ]; then
		executive="vykdomas"
	else
		executive="nevykdomas"
	fi

	echo $v " >> " $readable "/" $executive
done
