#! /bin/bash

user_found=false

while [ "$user_found" = false ]; do
	for i in $*; do
		if [ "$(who | grep $i | awk '{ print $1 }')" = "$i" ]; then
			echo "Naudotojas $i yra prisijunges"
			user_found=true
			break
		fi
	done

	if [ "$user_found" = false ]; then
		echo "Neprisijunges nei vienas"
		sleep 5
	fi
done
