#! /bin/bash

numbers="40 3 2 5 5 7 2 43 23 11 444 999 40 666 13"

echo $numbers

first=$( echo $numbers | awk '{ print $1 }' )

less=""
moreeq=""

for v in $numbers; do
	if [ $v -lt $first ]; then
		less="$less $v"
	else
		moreeq="$moreeq $v"
	fi
done

echo "Mazesni uz pirma: " $less
echo "Didesni ir lygus pirmam: " $moreeq
