#!/bin/sh

Funkcija(){
	awk '{ print $1, $3 }' prisijunge > data.log

        sort data.log | uniq -c | sort -nr | awk '{ if ( $1 < 5 ) print $0 }' > temp

        awk '{ print $1, $3 }' prisijunge > data.log

        sort data.log | uniq -c | sort -nr | awk '{ if ( $1 < 5 ) print $0 }' > temp

        echo MAZIAU NEI 5 KARTUS JUNGESI: `awk '{ print NR }' temp | tail -1`

        sort data.log | uniq -c | sort -nr > temp

        if [ -d users ];
        then
            	rm -r users
        fi

	mkdir users

        for i in `awk '{ print $2 }' temp`;
        do
          	if ! ls users | grep "^$i$";
                then
                    	touch users/$i.log
                        echo IP adresai, is kuriu $i jungesi daugiau nei vienakarta: > users/$i.log
                        awk -v i=$i '{ if ( $1 > 1 && $2 == i ) print $3 }' temp >> users/$i.log
                fi
        done

	rm temp
        rm prisijunge
}

if [ ! -d $1 ] && [ $# -gt 0 ];
then
	if [ ! -f $1 ];
	then
		touch report.txt
		touch names
		touch result
		for i in $*;
		do
			if ! grep "^$i$" names;
			then
				echo $i >> names
				grep "Accepted password for" /data/ld/ld2/studlog | awk -v i="$i" '{ if ( $(NF - 5) == i ) print i, $(NF - 3) }' >> report.txt
			fi
		done
		sort report.txt | uniq > result
		cat result > report.txt
		rm result
	else
		grep "Accepted password for" $1 | awk -F "Accepted password for" '{ print $2 }' > prisijunge
		Funkcija
	fi
else
	grep "Accepted password for" /data/ld/ld2/studlog | awk -F "Accepted password for" '{ print $2 }' > prisijunge
	Funkcija
fi

rm names
